<a href="https://colab.research.google.com/github/daapontet/MetNumUN2022II/blob/main/LAB_2/daapontet_Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install -U fortran-magic

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 1.6 MB 4.2 MB/s 


In [ ]:
%matplotlib inline
%load_ext fortranmagic

import sys; sys.path.append('..')

import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

mpl.rc('figure', figsize=(12, 7))

ran_the_first_cell = True

jan2017 = pd.to_datetime(['2017-01-03 00:00:00+00:00',
 '2017-01-04 00:00:00+00:00',
 '2017-01-05 00:00:00+00:00',
 '2017-01-06 00:00:00+00:00',
 '2017-01-09 00:00:00+00:00',
 '2017-01-10 00:00:00+00:00',
 '2017-01-11 00:00:00+00:00',
 '2017-01-12 00:00:00+00:00',
 '2017-01-13 00:00:00+00:00',
 '2017-01-17 00:00:00+00:00',
 '2017-01-18 00:00:00+00:00',
 '2017-01-19 00:00:00+00:00',
 '2017-01-20 00:00:00+00:00',
 '2017-01-23 00:00:00+00:00',
 '2017-01-24 00:00:00+00:00',
 '2017-01-25 00:00:00+00:00',
 '2017-01-26 00:00:00+00:00',
 '2017-01-27 00:00:00+00:00',
 '2017-01-30 00:00:00+00:00',
 '2017-01-31 00:00:00+00:00',
 '2017-02-01 00:00:00+00:00'])
calendar = jan2017.values.astype('datetime64[D]')

event_dates = pd.to_datetime(['2017-01-06 00:00:00+00:00', 
                             '2017-01-07 00:00:00+00:00', 
                             '2017-01-08 00:00:00+00:00']).values.astype('datetime64[D]')
event_values = np.array([10, 15, 20])

/usr/local/lib/python3.7/dist-packages/fortranmagic.py:147: UserWarning: get_ipython_cache_dir has moved to the IPython.paths module since IPython 4.0.
  self._lib_dir = os.path.join(get_ipython_cache_dir(), 'fortran')


<center>
  <h1>The PyData Toolbox</h1>
  <h3>Scott Sanderson (Twitter: @scottbsanderson, GitHub: ssanderson)</h3>
  <h3><a href="https://github.com/ssanderson/pydata-toolbox">https://github.com/ssanderson/pydata-toolbox</a></h3>
</center>

# About Me:

<img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/me.jpg" alt="Drawing" style="width: 300px;"/>

- Senior Engineer at [Quantopian](www.quantopian.com)
- Background in Mathematics and Philosophy
- **Twitter:** [@scottbsanderson](https://twitter.com/scottbsanderson)
- **GitHub:** [ssanderson](github.com/ssanderson)

## Outline

- Built-in Data Structures
- Numpy `array`
- Pandas `Series`/`DataFrame`
- Plotting and "Real-World" Analyses

# Data Structures

> Rule 5. Data dominates. If you've chosen the right data structures and organized things well, the algorithms
will almost always be self-evident. Data structures, not algorithms, are central to programming.

- *Notes on Programming in C*, by Rob Pike.

# Lists

In [ ]:
assert ran_the_first_cell, "Oh noes!"

In [ ]:
l = [1, 'two', 3.0, 4, 5.0, "six"]
l

[1, 'two', 3.0, 4, 5.0, 'six']

In [ ]:
# Lists can be indexed like C-style arrays.
first = l[0]
second = l[1]
print("first:", first)
print("second:", second)

first: 1
second: two


In [ ]:
# Negative indexing gives elements relative to the end of the list.
last = l[-1]
penultimate = l[-2]
print("last:", last)
print("second to last:", penultimate)

last: six
second to last: 5.0


In [ ]:
# Lists can also be sliced, which makes a copy of elements between 
# start (inclusive) and stop (exclusive)
sublist = l[1:3]
sublist

['two', 3.0]

In [ ]:
# l[:N] is equivalent to l[0:N].
first_three = l[:3]
first_three

[1, 'two', 3.0]

In [ ]:
# l[3:] is equivalent to l[3:len(l)].
after_three = l[3:]
after_three

[4, 5.0, 'six']

In [ ]:
# There's also a third parameter, "step", which gets every Nth element.
l = ['a', 'b', 'c', 'd', 'e', 'f', 'g','h']
l[1:7:2]

['b', 'd', 'f']

In [ ]:
# This is a cute way to reverse a list.
l[::-1]

['h', 'g', 'f', 'e', 'd', 'c', 'b', 'a']

In [ ]:
# Lists can be grown efficiently (in O(1) amortized time).
l = [1, 2, 3, 4, 5]
print("Before:", l)
l.append('six')
print("After:", l)

Before: [1, 2, 3, 4, 5]
After: [1, 2, 3, 4, 5, 'six']


In [ ]:
# Comprehensions let us perform elementwise computations.
l = [1, 2, 3, 4, 5]
[x * 2 for x in l]

[2, 4, 6, 8, 10]

## Review: Python Lists

- Zero-indexed sequence of arbitrary Python values.
- Slicing syntax: `l[start:stop:step]` copies elements at regular intervals from `start` to `stop`.
- Efficient (`O(1)`) appends and removes from end.
- Comprehension syntax: `[f(x) for x in l if cond(x)]`.

# Dictionaries

In [ ]:
# Dictionaries are key-value mappings.
philosophers = {'David': 'Hume', 'Immanuel': 'Kant', 'Bertrand': 'Russell'}
philosophers

{'David': 'Hume', 'Immanuel': 'Kant', 'Bertrand': 'Russell'}

In [ ]:
# Like lists, dictionaries are size-mutable.
philosophers['Ludwig'] = 'Wittgenstein'
philosophers

{'David': 'Hume',
 'Immanuel': 'Kant',
 'Bertrand': 'Russell',
 'Ludwig': 'Wittgenstein'}

In [ ]:
del philosophers['David']
philosophers

{'Immanuel': 'Kant', 'Bertrand': 'Russell', 'Ludwig': 'Wittgenstein'}

In [ ]:
# No slicing.
philosophers['Bertrand':'Immanuel']

TypeError: ignored

## Review: Python Dictionaries

- Unordered key-value mapping from (almost) arbitrary keys to arbitrary values.
- Efficient (`O(1)`) lookup, insertion, and deletion.
- No slicing (would require a notion of order).

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/pacino.gif" alt="Drawing" style="width: 100%;"/></center>


In [ ]:
# Suppose we have some matrices...
a = [[1, 2, 3],
     [2, 3, 4],
     [5, 6, 7],
     [1, 1, 1]]

b = [[1, 2, 3, 4],
     [2, 3, 4, 5]]

In [ ]:
def matmul(A, B):
    """Multiply matrix A by matrix B."""
    rows_out = len(A)
    cols_out = len(B[0])
    out = [[0 for col in range(cols_out)] for row in range(rows_out)]
    
    for i in range(rows_out):
        for j in range(cols_out):
            for k in range(len(B)):
                out[i][j] += A[i][k] * B[k][j]
    return out

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/gross.gif" alt="Drawing" style="width: 50%;"/></center>


In [ ]:
%%time

matmul(a, b)

CPU times: user 38 µs, sys: 6 µs, total: 44 µs
Wall time: 50.3 µs


[[5, 8, 11, 14], [8, 13, 18, 23], [17, 28, 39, 50], [3, 5, 7, 9]]

**My own example 1**

In [ ]:
def matmul(A, B):

    #Review A and B dimensions 
    if (len(A[0]) != len(B)): 
      return 'Incorrect matrices dimensions'

    """Multiply matrix A by matrix B."""
    rows_out = len(A)
    cols_out = len(B[0])
    out = [[0 for col in range(cols_out)] for row in range(rows_out)]
    
    for i in range(rows_out):
        for j in range(cols_out):
            for k in range(len(B)):
                out[i][j] += A[i][k] * B[k][j]
    return out

**My own example 2**

In [ ]:
%%time

matmul(a, b)

CPU times: user 7 µs, sys: 1e+03 ns, total: 8 µs
Wall time: 11.9 µs


'Incorrect matrices dimensions'

**My own example 3**

In [ ]:
C = [[10, 23, 33],
     [21, 36, 45],
     [55, 67, 78]]

D = [[12, 26, 37],
     [28, 38, 49], 
     [76, 56, 98]]

**My own example 4**

In [ ]:
%%time
matmul(C, D)

CPU times: user 53 µs, sys: 7 µs, total: 60 µs
Wall time: 198 µs


[[3272, 2982, 4731], [4680, 4434, 6951], [8464, 8344, 12962]]

In [ ]:
import random
def random_matrix(m, n):
    out = []
    for row in range(m):
        out.append([random.random() for _ in range(n)])
    return out

randm = random_matrix(2, 3)
randm

[[0.834473080962591, 0.14907478155570308, 0.04955575953884139],
 [0.30065168296228484, 0.11993132090125458, 0.11654556174321984]]

In [ ]:
%%time
randa = random_matrix(600, 100)
randb = random_matrix(100, 600)
x = matmul(randa, randb)

CPU times: user 7.18 s, sys: 41.5 ms, total: 7.23 s
Wall time: 7.27 s


**My own example 5**

In [ ]:
%%time
randC = random_matrix(600, 100)
randD = random_matrix(99, 600)
x = matmul(randC, randD)
x

CPU times: user 23.3 ms, sys: 6.98 ms, total: 30.2 ms
Wall time: 30.2 ms


'Incorrect matrices dimensions'

**My own example 6**

In [ ]:
%%time
randC = random_matrix(300, 300)
randD = random_matrix(300, 300)
x = matmul(randa, randb)

CPU times: user 7.8 s, sys: 34.2 ms, total: 7.84 s
Wall time: 7.88 s


In [ ]:
# Maybe that's not that bad?  Let's try a simpler case.
def python_dot_product(xs, ys):
    return sum(x * y for x, y in zip(xs, ys))

In [ ]:
%%fortran
subroutine fortran_dot_product(xs, ys, result)
    double precision, intent(in) :: xs(:)
    double precision, intent(in) :: ys(:)
    double precision, intent(out) :: result
    
    result = sum(xs * ys)
end

In [ ]:
list_data = [float(i) for i in range(100000)]
array_data = np.array(list_data)

**My oewn example 7**

In [ ]:
list_data_2 = [float(j) for j in range(300000)]
array_data_2 = np.array(list_data_2)

In [ ]:
%%time
python_dot_product(list_data, list_data)

CPU times: user 7.8 ms, sys: 0 ns, total: 7.8 ms
Wall time: 7.73 ms


333328333350000.0

**My own example 8**

In [ ]:
%%time
python_dot_product(list_data_2, list_data_2)

CPU times: user 27.1 ms, sys: 0 ns, total: 27.1 ms
Wall time: 28.9 ms


8999955000050000.0

In [ ]:
%%time
fortran_dot_product(array_data, array_data)

CPU times: user 141 µs, sys: 5 µs, total: 146 µs
Wall time: 149 µs


333328333350000.0

**My own example 9**

In [ ]:
%%time
fortran_dot_product(array_data, array_data)

CPU times: user 169 µs, sys: 0 ns, total: 169 µs
Wall time: 173 µs


333328333350000.0

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/sloth.gif" alt="Drawing" style="width: 1080px;"/></center>


## Why is the Python Version so Much Slower?

In [ ]:
# Dynamic typing.
def mul_elemwise(xs, ys):
    return [x * y for x, y in zip(xs, ys)]

mul_elemwise([1, 2, 3, 4], [1, 2 + 0j, 3.0, 'four'])
#[type(x) for x in _]

[1, (4+0j), 9.0, 'fourfourfourfour']

**My own example 10**

In [ ]:
mul_elemwise([4, 3, 2, 1], [True, 1j, 'Double', False])

[4, 3j, 'DoubleDouble', 0]

In [ ]:
# Interpretation overhead.
source_code = 'a + b * c'
bytecode = compile(source_code, '', 'eval')
import dis; dis.dis(bytecode)

  1           0 LOAD_NAME                0 (a)
              2 LOAD_NAME                1 (b)
              4 LOAD_NAME                2 (c)
              6 BINARY_MULTIPLY
              8 BINARY_ADD
             10 RETURN_VALUE


**My own example 12**

In [ ]:
source_code_2 = 'a * False'
bytecode = compile(source_code_2, '', 'eval')
dis.dis(bytecode)

  1           0 LOAD_NAME                0 (a)
              2 LOAD_CONST               0 (False)
              4 BINARY_MULTIPLY
              6 RETURN_VALUE


## Why is the Python Version so Slow?
- Dynamic typing means that every single operation requires dispatching on the input type.
- Having an interpreter means that every instruction is fetched and dispatched at runtime.
- Other overheads:
  - Arbitrary-size integers.
  - Reference-counted garbage collection.

> This is the paradox that we have to work with when we're doing scientific or numerically-intensive Python. What makes Python fast for development -- this high-level, interpreted, and dynamically-typed aspect of the language -- is exactly what makes it slow for code execution.

- Jake VanderPlas, [*Losing Your Loops: Fast Numerical Computing with NumPy*](https://www.youtube.com/watch?v=EEUXKG97YRw)

# What Do We Do?

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/runaway.gif" alt="Drawing" style="width: 50%;"/></center>

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/thisisfine.gif" alt="Drawing" style="width: 1080px;"/></center>

- Python is slow for numerical computation because it performs dynamic dispatch on every operation we perform...

- ...but often, we just want to do the same thing over and over in a loop!

- If we don't need Python's dynamicism, we don't want to pay (much) for it.

- **Idea:** Dispatch **once per operation** instead of **once per element**.

In [ ]:
import numpy as np

data = np.array([1, 2, 3, 4])
data

array([1, 2, 3, 4])

**My own example 13**

In [ ]:
data2 = np.array([5,300,42])

In [ ]:
data + data

array([2, 4, 6, 8])

In [ ]:
%%time
# Naive dot product
(array_data * array_data).sum()

CPU times: user 530 µs, sys: 0 ns, total: 530 µs
Wall time: 631 µs


333328333350000.0

**My own example 14**

In [ ]:
%%time
(array_data_2 * array_data_2).sum()

CPU times: user 6.14 ms, sys: 999 µs, total: 7.13 ms
Wall time: 7.45 ms


8999955000050000.0

In [ ]:
%%time
# Built-in dot product.
array_data.dot(array_data)

CPU times: user 345 µs, sys: 0 ns, total: 345 µs
Wall time: 235 µs


333328333350000.0

**My own example 15**

In [ ]:
%%time
array_data_2.dot(array_data_2)

CPU times: user 4.87 ms, sys: 0 ns, total: 4.87 ms
Wall time: 3.77 ms


8999955000050000.0

In [ ]:
%%time
fortran_dot_product(array_data, array_data)

CPU times: user 152 µs, sys: 6 µs, total: 158 µs
Wall time: 165 µs


333328333350000.0

**My own example 16**

In [ ]:
%%time
fortran_dot_product(array_data_2, array_data_2)

CPU times: user 0 ns, sys: 663 µs, total: 663 µs
Wall time: 538 µs


8999955000050000.0

In [ ]:
# Numpy won't allow us to write a string into an int array.
data[0] = "foo"

ValueError: ignored

In [ ]:
# We also can't grow an array once it's created.
data.append(3)

AttributeError: ignored

In [ ]:
# We **can** reshape an array though.
two_by_two = data.reshape(2, 2)
two_by_two

array([[1, 2],
       [3, 4]])

Numpy arrays are:

- Fixed-type

- Size-immutable

- Multi-dimensional

- Fast\*

\* If you use them correctly.

# What's in an Array?

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6], dtype='int16').reshape(2, 3)
print("Array:\n", arr, sep='')
print("===========")
print("DType:", arr.dtype)
print("Shape:", arr.shape)
print("Strides:", arr.strides)
print("Data:", arr.data.tobytes())

Array:
[[1 2 3]
 [4 5 6]]
DType: int16
Shape: (2, 3)
Strides: (6, 2)
Data: b'\x01\x00\x02\x00\x03\x00\x04\x00\x05\x00\x06\x00'


# Core Operations

- Vectorized **ufuncs** for elementwise operations.
- Fancy indexing and masking for selection and filtering.
- Aggregations across axes.
- Broadcasting

# UFuncs

UFuncs (universal functions) are functions that operate elementwise on one or more arrays.

In [ ]:
data = np.arange(15).reshape(3, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
# Binary operators.
data * data

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]])

In [ ]:
# Unary functions.
np.sqrt(data)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739]])

In [ ]:
# Comparison operations
(data % 3) == 0

array([[ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False]])

In [ ]:
# Boolean combinators.
((data % 2) == 0) & ((data % 3) == 0)

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False]])

In [ ]:
# as of python 3.5, @ is matrix-multiply
data @ data.T

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

# UFuncs Review

- UFuncs provide efficient elementwise operations applied across one or more arrays.
- Arithmetic Operators (`+`, `*`, `/`)
- Comparisons (`==`, `>`, `!=`)
- Boolean Operators (`&`, `|`, `^`)
- Trigonometric Functions (`sin`, `cos`)
- Transcendental Functions (`exp`, `log`)

# Selections

We often want to perform an operation on just a subset of our data.

In [ ]:
sines = np.sin(np.linspace(0, 3.14, 10))
cosines = np.cos(np.linspace(0, 3.14, 10))
sines

array([0.        , 0.34185385, 0.64251645, 0.86575984, 0.98468459,
       0.98496101, 0.8665558 , 0.64373604, 0.34335012, 0.00159265])

In [ ]:
# Slicing works with the same semantics as Python lists.
sines[0]

0.0

In [ ]:
sines[:3]  # First three elements  

array([0.        , 0.34185385, 0.64251645])

In [ ]:
sines[5:]  # Elements from 5 on.

array([0.98496101, 0.8665558 , 0.64373604, 0.34335012, 0.00159265])

In [ ]:
sines[::2]  # Every other element.

array([0.        , 0.64251645, 0.98468459, 0.8665558 , 0.34335012])

In [ ]:
# More interesting: we can index with boolean arrays to filter by a predicate.
print("sines:\n", sines)
print("sines > 0.5:\n", sines > 0.5)
print("sines[sines > 0.5]:\n", sines[sines > 0.5])

sines:
 [0.         0.34185385 0.64251645 0.86575984 0.98468459 0.98496101
 0.8665558  0.64373604 0.34335012 0.00159265]
sines > 0.5:
 [False False  True  True  True  True  True  True False False]
sines[sines > 0.5]:
 [0.64251645 0.86575984 0.98468459 0.98496101 0.8665558  0.64373604]


In [ ]:
# We index with lists/arrays of integers to select values at those indices.
print(sines)
sines[[0, 4, 7]]

[0.         0.34185385 0.64251645 0.86575984 0.98468459 0.98496101
 0.8665558  0.64373604 0.34335012 0.00159265]


array([0.        , 0.98468459, 0.64373604])

In [ ]:
# Index arrays are often used for sorting one or more arrays.
unsorted_data = np.array([1, 3, 2, 12, -1, 5, 2])

In [ ]:
sort_indices = np.argsort(unsorted_data)
sort_indices

array([4, 0, 2, 6, 1, 5, 3])

In [ ]:
unsorted_data[sort_indices]

array([-1,  1,  2,  2,  3,  5, 12])

In [ ]:
market_caps = np.array([12, 6, 10, 5, 6])  # Presumably in dollars?
assets = np.array(['A', 'B', 'C', 'D', 'E'])

In [ ]:
# Sort assets by market cap by using the permutation that would sort market caps on ``assets``.
sort_by_mcap = np.argsort(market_caps)
assets[sort_by_mcap]

array(['D', 'B', 'E', 'C', 'A'], dtype='<U1')

In [ ]:
# Indexers are also useful for aligning data.
print("Dates:\n", repr(event_dates))
print("Values:\n", repr(event_values))
print("Calendar:\n", repr(calendar))

Dates:
 array(['2017-01-06', '2017-01-07', '2017-01-08'], dtype='datetime64[D]')
Values:
 array([10, 15, 20])
Calendar:
 array(['2017-01-03', '2017-01-04', '2017-01-05', '2017-01-06',
       '2017-01-09', '2017-01-10', '2017-01-11', '2017-01-12',
       '2017-01-13', '2017-01-17', '2017-01-18', '2017-01-19',
       '2017-01-20', '2017-01-23', '2017-01-24', '2017-01-25',
       '2017-01-26', '2017-01-27', '2017-01-30', '2017-01-31',
       '2017-02-01'], dtype='datetime64[D]')


In [ ]:
print("Raw Dates:", event_dates)
print("Indices:", calendar.searchsorted(event_dates))
print("Forward-Filled Dates:", calendar[calendar.searchsorted(event_dates)])

Raw Dates: ['2017-01-06' '2017-01-07' '2017-01-08']
Indices: [3 4 4]
Forward-Filled Dates: ['2017-01-06' '2017-01-09' '2017-01-09']


On multi-dimensional arrays, we can slice along each axis independently.

In [ ]:
data = np.arange(25).reshape(5, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
data[:2, :2]  # First two rows and first two columns.

array([[0, 1],
       [5, 6]])

In [ ]:
data[:2, [0, -1]]  # First two rows, first and last columns.

array([[0, 4],
       [5, 9]])

In [ ]:
data[(data[:, 0] % 2) == 0]  # Rows where the first column is divisible by two.

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

# Selections Review

- Indexing with an integer removes a dimension.
- Slicing operations work on Numpy arrays the same way they do on lists.
- Indexing with a boolean array filters to True locations.
- Indexing with an integer array selects indices along an axis.
- Multidimensional arrays can apply selections independently along different axes.

## Reductions

Functions that reduce an array to a scalar.

$Var(X) = \frac{1}{N}\sqrt{\sum_{i=1}^N (x_i - \bar{x})^2}$

In [ ]:
def variance(x):
    return ((x - x.mean()) ** 2).sum() / len(x)

In [ ]:
variance(np.random.standard_normal(1000))

0.9963420972627446

- `sum()` and `mean()` are both **reductions**.

- In the simplest case, we use these to reduce an entire array into a single value...

In [ ]:
data = np.arange(30)
data.mean()

14.5

- ...but we can do more interesting things with multi-dimensional arrays.

In [ ]:
data = np.arange(30).reshape(3, 10)
data

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [ ]:
data.mean()

14.5

In [ ]:
data.mean(axis=0)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

In [ ]:
data.mean(axis=1)

array([ 4.5, 14.5, 24.5])

## Reductions Review

- Reductions allow us to perform efficient aggregations over arrays.
- We can do aggregations over a single axis to collapse a single dimension.
- Many built-in reductions (`mean`, `sum`, `min`, `max`, `median`, ...).

# Broadcasting

In [ ]:
row = np.array([1, 2, 3, 4])
column = np.array([[1], [2], [3]])
print("Row:\n", row, sep='')
print("Column:\n", column, sep='')

Row:
[1 2 3 4]
Column:
[[1]
 [2]
 [3]]


In [ ]:
row + column

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/broadcasting.png" alt="Drawing" style="width: 60%;"/></center>

<h5>Source: http://www.scipy-lectures.org/_images/numpy_broadcasting.png</h5>

In [ ]:
# Broadcasting is particularly useful in conjunction with reductions.
print("Data:\n", data, sep='')
print("Mean:\n", data.mean(axis=0), sep='')
print("Data - Mean:\n", data - data.mean(axis=0), sep='')

Data:
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
Mean:
[10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
Data - Mean:
[[-10. -10. -10. -10. -10. -10. -10. -10. -10. -10.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 10.  10.  10.  10.  10.  10.  10.  10.  10.  10.]]


# Broadcasting Review

- Numpy operations can work on arrays of different dimensions as long as the arrays' shapes are still "compatible".
- Broadcasting works by "tiling" the smaller array along the missing dimension.
- The result of a broadcasted operation is always at least as large in each dimension as the largest array in that dimension.

# Numpy Review

- Numerical algorithms are slow in pure Python because the overhead dynamic dispatch dominates our runtime.

- Numpy solves this problem by:
  1. Imposing additional restrictions on the contents of arrays.
  2. Moving the inner loops of our algorithms into compiled C code.

- Using Numpy effectively often requires reworking an algorithms to use vectorized operations instead of for-loops, but the resulting operations are usually simpler, clearer, and faster than the pure Python equivalent.

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/unicorn.jpg" alt="Drawing" style="width: 75%;"/></center>

Numpy is great for many things, but...

- Sometimes our data is equipped with a natural set of **labels**:
  - Dates/Times
  - Stock Tickers
  - Field Names (e.g. Open/High/Low/Close)

- Sometimes we have **more than one type of data** that we want to keep grouped together.
  - Tables with a mix of real-valued and categorical data.

- Sometimes we have **missing** data, which we need to ignore, fill, or otherwise work around.

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/panda-wrangling.gif" alt="Drawing" style="width: 75%;"/></center>

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/pandas_logo.png" alt="Drawing" style="width: 75%;"/></center>


Pandas extends Numpy with more complex data structures:

- `Series`: 1-dimensional, homogenously-typed, labelled array.
- `DataFrame`: 2-dimensional, semi-homogenous, labelled table.

Pandas also provides many utilities for: 
- Input/Output
- Data Cleaning
- Rolling Algorithms
- Plotting

# Selection in Pandas

In [ ]:
s = pd.Series(index=['a', 'b', 'c', 'd', 'e'], data=[1, 2, 3, 4, 5])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [ ]:
# There are two pieces to a Series: the index and the values.
print("The index is:", s.index)
print("The values are:", s.values)

The index is: Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
The values are: [1 2 3 4 5]


In [ ]:
# We can look up values out of a Series by position...
s.iloc[0]

1

In [ ]:
# ... or by label.
s.loc['a']

1

In [ ]:
# Slicing works as expected...
s.iloc[:2]

a    1
b    2
dtype: int64

In [ ]:
# ...but it works with labels too!
s.loc[:'c']

a    1
b    2
c    3
dtype: int64

In [ ]:
# Fancy indexing works the same as in numpy.
s.iloc[[0, -1]]

a    1
e    5
dtype: int64

In [ ]:
# As does boolean masking.
s.loc[s > 2]

c    3
d    4
e    5
dtype: int64

In [ ]:
# Element-wise operations are aligned by index.
other_s = pd.Series({'a': 10.0, 'c': 20.0, 'd': 30.0, 'z': 40.0})
other_s

a    10.0
c    20.0
d    30.0
z    40.0
dtype: float64

In [ ]:
s + other_s

a    11.0
b     NaN
c    23.0
d    34.0
e     NaN
z     NaN
dtype: float64

In [ ]:
# We can fill in missing values with fillna().
(s + other_s).fillna(0.0)

a    11.0
b     0.0
c    23.0
d    34.0
e     0.0
z     0.0
dtype: float64

In [ ]:
# Most real datasets are read in from an external file format.
aapl = pd.read_csv('AAPL.csv', parse_dates=['Date'], index_col='Date')
aapl.head()

FileNotFoundError: ignored

In [ ]:
# Slicing generalizes to two dimensions as you'd expect:
aapl.iloc[:2, :2]

NameError: ignored

In [ ]:
aapl.loc[pd.Timestamp('2010-02-01'):pd.Timestamp('2010-02-04'), ['Close', 'Volume']]

NameError: ignored

# Rolling Operations

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/rolling.gif" alt="Drawing" style="width: 75%;"/></center>

In [ ]:
aapl.rolling(5)[['Close', 'Adj Close']].mean().plot();

In [ ]:
# Drop `Volume`, since it's way bigger than everything else.
aapl.drop('Volume', axis=1).resample('2W').max().plot();

In [ ]:
# 30-day rolling exponentially-weighted stddev of returns.
aapl['Close'].pct_change().ewm(span=30).std().plot();

# "Real World" Data

In [ ]:
from io import BytesIO
import os
from urllib.parse import urlencode

import requests
import numpy as np
import pandas as pd


def read_avocadata(start_date, end_date, cache_loc='avocadata.html'):
    """Download avocado data to a dataframe.
    Parameters
    ----------
    """
    start_date = pd.Timestamp(start_date)
    end_date = pd.Timestamp(end_date)
    base_url = 'https://www.marketnews.usda.gov/mnp/fv-report-retail'
    query_params = {
        'class': ['FRUITS'],
        'commodity': ['AVOCADOS'],
        'compareLy': ['No'],
        'endDate': [end_date.strftime("%m/%d/%Y")],
        'format': ['excel'],
        'organic': ['ALL'],
        'portal': ['fv'],
        'region': ['ALL'],
        'repDate': [start_date.strftime("%m/%d/%Y")],
        'type': ['retail'],
    }

    url = base_url + '?' + urlencode(query_params, doseq=1)

    if not os.path.exists(cache_loc):
        resp = requests.get(url, stream=True)
        resp.raise_for_status()

        with open(cache_loc, 'wb') as f:
            for block in resp.iter_content(chunk_size=4096):
                f.write(block)
        f.close()

    with open(cache_loc, 'rb') as f:
        frame = pd.read_html(f, header=0)[0]

    # Cleanup
    frame = frame[frame['Unit'] == 'each']
    frame['Organic'] = (frame['Organic'] == 'Y')
    frame['Variety'].replace(
        {'VARIOUS GREENSKIN VARIETIES': 'GREENSKIN'},
        inplace=True,
    )
    frame['Date'] = pd.to_datetime(frame['Date'].values, utc=True)

    frame['Region'] = frame['Region'].str.replace(' U.S.', '')
    frame['Region'] = frame['Region'].str.replace(' ', '_')

    # Drop useless columns.
    return frame.drop(
        ['Class', 'Commodity', 'Environment', 'Unit', '% Marked Local'],
        axis=1,
    )

In [ ]:
avocados = read_avocadata('2014', '2016')
avocados.head()

In [ ]:
# Unlike numpy arrays, pandas DataFrames can have a different dtype for each column.
avocados.dtypes

In [ ]:
# What's the regional average price of a HASS avocado every day?
hass = avocados[avocados.Variety == 'HASS']
hass.groupby(['Date', 'Region'])['Weighted Avg Price'].mean().unstack().ffill().plot();

In [ ]:
def _organic_spread(group):

    if len(group.columns) != 2:
        return pd.Series(index=group.index, data=0.0)
    
    is_organic = group.columns.get_level_values('Organic').values.astype(bool)
    organics = group.loc[:, is_organic].squeeze()
    non_organics = group.loc[:, ~is_organic].squeeze()
    diff = organics - non_organics
    return diff

def organic_spread_by_region(df):
    """What's the difference between the price of an organic 
    and non-organic avocado within each region?
    """
    return (
        df
        .set_index(['Date', 'Region', 'Organic'])
         ['Weighted Avg Price']
        .unstack(level=['Region', 'Organic'])
        .ffill()
        .groupby(level='Region', axis=1)
        .apply(_organic_spread)
    )

In [ ]:
organic_spread_by_region(hass).plot();
plt.gca().set_title("Daily Regional Organic Spread");
plt.legend(bbox_to_anchor=(1, 1));

In [ ]:
spread_correlation = organic_spread_by_region(hass).corr()
spread_correlation

In [ ]:
import seaborn as sns
grid = sns.clustermap(spread_correlation, annot=True)
fig = grid.fig
axes = fig.axes
ax = axes[2]
ax.set_xticklabels(ax.get_xticklabels(), rotation=45);

# Pandas Review

- Pandas extends numpy with more complex datastructures and algorithms.
- If you understand numpy, you understand 90% of pandas.
- `groupby`, `set_index`, and `unstack` are powerful tools for working with categorical data.
- Avocado prices are surprisingly interesting :)

# Matrix Multiplication averages
- Write code for matrix multiplication in NumPy, C,C++, Java Script and Java  and run all the codes in all languages for 10 times and the same 600×100 and 100×100 matrices used in Python measuring and collecting the running times. Build a data fame with the average times and the speed factor respect to the language that is faster.


**My own example 18**

Python average

In [ ]:
#Python Matrix multiplication 
%%time
A = random_matrix(600, 100)
B = random_matrix(100, 100)
X = matmul(A, B)

In [ ]:
#Python Matrix multiplication 
%%time
A = random_matrix(600, 100)
B = random_matrix(100, 100)
X = matmul(A, B)

In [ ]:
#Python Matrix multiplication 
%%time
A = random_matrix(600, 100)
B = random_matrix(100, 100)
X = matmul(A, B)

In [ ]:
#Python Matrix multiplication 
%%time
A = random_matrix(600, 100)
B = random_matrix(100, 100)
X = matmul(A, B)

In [ ]:
#Python Matrix multiplication 
%%time
A = random_matrix(600, 100)
B = random_matrix(100, 100)
X = matmul(A, B)

In [ ]:
#Python Matrix multiplication 
%%time
A = random_matrix(600, 100)
B = random_matrix(100, 100)
X = matmul(A, B)

In [ ]:
#Python Matrix multiplication 
%%time
A = random_matrix(600, 100)
B = random_matrix(100, 100)
X = matmul(A, B)

In [ ]:
#Python Matrix multiplication 
%%time
A = random_matrix(600, 100)
B = random_matrix(100, 100)
X = matmul(A, B)

In [ ]:
#Python Matrix multiplication 
%%time
A = random_matrix(600, 100)
B = random_matrix(100, 100)
X = matmul(A, B)

In [ ]:
#Python Matrix multiplication 
%%time
A = random_matrix(600, 100)
B = random_matrix(100, 100)
X = matmul(A, B)

In [ ]:
#Python Matrix multiplication 
%%time
A = random_matrix(600, 100)
B = random_matrix(100, 100)
X = matmul(A, B)

In [ ]:
python_average = (1.44 + 1.31 + 1.85 + 1.74 + 1.79 + 1.65 + 1.79 + 1.88 + 1.87 + 1.71 + 1.71)/10
python_average = python_average * 1000 #Change seconds to ms
python_average

C average

In [ ]:
%%writefile tmpc.c

#include<stdio.h>    
#include<stdlib.h>  

int main(){  

  float A[600][100]; 
  float B[100][100];
  float mul[100][100];
  int r = 600;
  int c = 100; 
  int i, j, k;   

  //Random A
  for(i = 0; i < 600; i++) {
    for(j = 0; j < 100; j++) {
      A[i][j] = (float) (rand() % 10000) / 10000;
    }
  }  

  //Random B
  for(i = 0; i < 100; i++) {
    for(j = 0; j < 100; j++) {
      B[i][j] = (float)(rand() % 10000) / 10000;
    }
  }  
      
  //matMulC  
  for(i = 0; i < r; i++) {    
    for(j = 0; j < c; j++) {    
      mul[i][j] = 0;    
      for(k = 0; k < c; k++) {  
        mul[i][j] += A[i][k] * B[k][j];    
      }    
    }    
  }    

  //Print matrix only for test   
  /*for(i = 0; i < r; i++) {    
    for( j = 0; j < c; j++) {    
      printf("%f\t", mul[i][j]);    
    }    
    printf("\n");    
  }*/

  return 0;  

}

In [ ]:
%%time
!gcc tmpc.c -o tmpc
!./tmpc

In [ ]:
%%time
!gcc tmpc.c -o tmpc
!./tmpc

In [ ]:
%%time
!gcc tmpc.c -o tmpc
!./tmpc

In [ ]:
%%time
!gcc tmpc.c -o tmpc
!./tmpc

In [ ]:
%%time
!gcc tmpc.c -o tmpc
!./tmpc

In [ ]:
%%time
!gcc tmpc.c -o tmpc
!./tmpc

In [ ]:
%%time
!gcc tmpc.c -o tmpc
!./tmpc

In [ ]:
%%time
!gcc tmpc.c -o tmpc
!./tmpc

In [ ]:
%%time
!gcc tmpc.c -o tmpc
!./tmpc

In [ ]:
%%time
!gcc tmpc.c -o tmpc
!./tmpc

In [ ]:
c_average = (23.7 + 21.4 + 25.4 + 21.6 + 23.6 + 24.2 + 27.2 + 23.9 + 23 + 30.7)/10
c_average

C++ average

In [ ]:
%%writefile tmpcc.cc
#include <iostream>
using namespace std;

int main() {
  
  float A[600][100]; 
  float B[100][100];
  float mul[100][100];
  int r = 600;
  int c = 100; 
  int i, j, k; 

  //Random A
  for(i = 0; i < 600; i++) {
    for(j = 0; j < 100; j++) {
      A[i][j] = (float) (rand() % 10000) / 10000;
    }
  }  

  //Random B
  for(i = 0; i < 100; i++) {
    for(j = 0; j < 100; j++) {
      B[i][j] = (float) (rand() % 10000) / 10000;
    }
  }      
      
  //matMulCpp
  for(i = 0; i < r; i++) {    
    for(j = 0; j < c; j++) {    
      mul[i][j] = 0;    
      for(k = 0; k < c; k++) {    
        mul[i][j] += A[i][k] * B[k][j];    
      }    
    }    
  }    

  //Print matrix only for test purpose
  /*for(i = 0; i < r; ++i) {
    for(j = 0; j < c; ++j) {
        cout << " " << mul[i][j];
        if(j == c-1) {
          cout << endl;
        }
    }
  }*/
	return 0;
}

In [ ]:
%%time
!g++ tmpcc.cc -o tmpcc
!./tmpcc

In [ ]:
%%time
!g++ tmpcc.cc -o tmpcc
!./tmpcc

In [ ]:
%%time
!g++ tmpcc.cc -o tmpcc
!./tmpcc

In [ ]:
%%time
!g++ tmpcc.cc -o tmpcc
!./tmpcc

In [ ]:
%%time
!g++ tmpcc.cc -o tmpcc
!./tmpcc

In [ ]:
%%time
!g++ tmpcc.cc -o tmpcc
!./tmpcc

In [ ]:
%%time
!g++ tmpcc.cc -o tmpcc
!./tmpcc

In [ ]:
%%time
!g++ tmpcc.cc -o tmpcc
!./tmpcc

In [ ]:
%%time
!g++ tmpcc.cc -o tmpcc
!./tmpcc

In [ ]:
%%time
!g++ tmpcc.cc -o tmpcc
!./tmpcc

In [ ]:
cpp_average = (25.3 + 32.7 + 21.3 + 22.6 + 25.1 + 28.2 + 25.5 + 27.2 + 26.7 + 27.1)/10
cpp_average

Js average 

In [ ]:
%%writefile tmp.js
var mul = [];
var A = []; 
var B = []; 
var i, j, k, r; 

//Random A
for(i = 0; i < 600; i++) {
    A[i] = []; 
    for(j = 0; j < 100; j++) {
      A[i][j] = Math.random();
    }
}

//Random B
for(i = 0; i < 100; i++) {
    B[i] = []; 
    for(j = 0; j < 100; j++) {
      B[i][j] = Math.random();
    }
}

//MatMul
for (i = 0; i < A.length; i++) {
    mul[i] = [];
    for (j = 0; j < B[0].length; j++) {
        var sum = 0;
        for (k = 0; k < A[0].length; k++) {
            sum += A[i][k] * B[k][j];
        }
        mul[i][j] = sum;
    }
}

// Print Matrix only for test
/*
for (r = 0; r < mul.length; r++) {
    console.log(mul[r]);
}
*/

In [ ]:
%%time
!node tmp.js

In [ ]:
%%time
!node tmp.js

In [ ]:
%%time
!node tmp.js

In [ ]:
%%time
!node tmp.js

In [ ]:
%%time
!node tmp.js

In [ ]:
%%time
!node tmp.js

In [ ]:
%%time
!node tmp.js

In [ ]:
%%time
!node tmp.js

In [ ]:
%%time
!node tmp.js

In [ ]:
%%time
!node tmp.js

In [ ]:
js_average = (12.8 + 14.9 + 13.9 + 10.8 + 9.82 + 14.9 + 10 + 11.4 + 11.1 + 10.1)/10
js_average

Java average 

In [ ]:
%%writefile Main.java

class Main {

  public static void main(String[] args) {

    int i, j, k; 
    double A[][] = new double[600][100]; 
    double B[][] = new double[100][100];
    double mul[][] = new double[600][100];

    //Random A 
    for (i = 0; i < 600; i++) {
      for (j = 0; j < 100; j++) {
        A[i][j] = Math.random();
      }
    }   

    //Random B
    for (i = 0; i < 100; i++) {
      for (j = 0; j < 100; j++) {
        B[i][j] = Math.random();
      }
    } 
            
    for(i = 0; i < 600; i++) {    
      for(j = 0; j < 100; j++) {    
        double sum = 0;      
        for(k = 0; k < 100; k++) {      
          sum += A[i][k] * B[k][j];      
        }
        mul[i][j] = sum; 
      } 
    }

    //Print only for test
    /*
    for (i = 0; i < 600; i++) {
      for (j = 0; j < 100; j++) {
        System.out.print(mul[i][j] + " ");   
      }
      System.out.println();
    }
    */

  }
}

In [ ]:
%%time
!javac Main.java
!java Main

In [ ]:
%%time
!javac Main.java
!java Main

In [ ]:
%%time
!javac Main.java
!java Main

In [ ]:
%%time
!javac Main.java
!java Main

In [ ]:
%%time
!javac Main.java
!java Main

In [ ]:
%%time
!javac Main.java
!java Main

In [ ]:
%%time
!javac Main.java
!java Main

In [ ]:
%%time
!javac Main.java
!java Main

In [ ]:
%%time
!javac Main.java
!java Main

In [ ]:
%%time
!javac Main.java
!java Main

In [ ]:
java_average = (30.9 + 27.9 + 32.9 + 35 + 28.8 + 28 + 27.9 + 32.5 + 31.2 + 28.2)/10
java_average

Dataframe and Plot

**My own example 19**

In [ ]:
fastest = min(python_average, c_average, cpp_average, js_average, java_average)
data = [[python_average, python_average/fastest], 
        [c_average, c_average/fastest], 
        [cpp_average, cpp_average/fastest], 
        [js_average, js_average/fastest], 
        [java_average, java_average/fastest]]
data

In [ ]:
df = pd.DataFrame(data, index=['Py', 'C', 'C++', 'Js', 'Java'], columns=['Average', 'SpeedFactor'])
df

In [ ]:
df["Average"].plot()

In [ ]:
df["SpeedFactor"].plot()

As python is the slowest then let's make another dataframe without it. 

In [ ]:
data2 = [[c_average, c_average/fastest], 
        [cpp_average, cpp_average/fastest], 
        [js_average, js_average/fastest], 
        [java_average, java_average/fastest]]
df2 = pd.DataFrame(data2, index=['C', 'C++', 'Js', 'Java'], columns=['Average', 'SpeedFactor'])
df2.plot()

# Avocado own example - Colombian Wheat example 
8. Include an analysis similar to the one performed with the avocados data using any data set

**My own example 21**

In [ ]:
# Got .xlsx File about wheat exportations from Colombia to US from: 
# https://apps.fas.usda.gov/esrquery/esrq.aspx

#Clean it 

#Install extension from pandas to read the file 

#Optional: In the repository of this laboratory is also the Data.xlsx file to upload it in Collab - Files - Content

In [ ]:
pip install --upgrade xlrd

In [ ]:
import pandas as pd

df = pd.read_excel('Data.xlsx')

print(df)

In [ ]:
#Clean data 
df.rename( columns={'Unnamed: 4':'Date'}, inplace=True )
df.rename( columns={'Unnamed: 6':'Country'}, inplace=True )
df.rename( columns={'Unnamed: 7':'Weekly Exports'}, inplace=True )
df.rename( columns={'Unnamed: 10':'Gross Sales'}, inplace=True )
df = df[["Date", "Country", "Weekly Exports", "Gross Sales"]]
df = df.drop(index = [0])
df

In [ ]:
df.groupby(['Date'])['Gross Sales'].mean().ffill().plot();
plt.gca().set_title("Average Gross Sales");

In [ ]:
df.groupby(['Date'])['Weekly Exports'].mean().ffill().plot();
plt.gca().set_title("Average Weekly Exports");

In [ ]:
#Country corr, as we have only one so Corr must be 1 

country_corr = df.set_index(['Date', 'Country'])['Gross Sales'].unstack(level=['Country']).ffill().groupby(level='Country', axis=1).corr()
country_corr

# Thanks!